export const roomTypes: AttributeList = {
    "Porch": 0.5,
    "Foyer": 0.5,
    "Cloak room": 0.5,
    "Gallery": 0.5,
    "Great hall": 0.5,
    "Dining hall": 0.5,
    "Ballroom": 0.5,
    "Piano room": 0.5,
    "Billiard room": 0.5,
    "Drawing room": 0.5,
    "Study": 0.5,
    "Library": 0.5,
    "Conservatory": 0.5,
    "Trophy room": 0.5,
    "Armory": 0.5,
    "Shooting range": 0.5,
    "Indoor Pool": 0.5,
    "Stables": 0.5,
    "Tack Room": 0.5,
    "Groom's room": 0.5,
    "Coach House": 0.5,
    "Servant's Quarters": 0.5,
    "Silver polishing room": 0.5,
    "Gift wrapping room": 0.5,
    "Canning room": 0.5,
    "Wine cellar": 0.5,
    "Root cellar": 0.5,
    "Larder": 0.5,
    "Pantry": 0.5,
    "Butler's pantry": 0.5,
    "Family kitchen": 0.5,
    "Personal Dining Room": 0.5,
    "Parlor": 0.5,
    "Master Bedroom": 0.5,
    "Guest Bedroom": 0.5,
    "Dressing Room": 0.5,
    "Powder Room": 0.5,
    "Master Bathroom": 0.5,
    "Guest Bathroom": 0.5,
    "Garret": 0.5,
    "Attic": 0.5,
    "Belvedere": 0.5,
    "Theater": 0.5,
    "Topiary Maze": 0.5,
    "Panic Room": 0.5,
    "Sub-Basement": 0.5,
    "Atrium": 0.5,
    "Boudoir": 0.5,
    "Chapel": 0.5,
    "Fainting Room": 0.5,
    "Furnace Room": 0.5,
    "Sauna": 0.5,
    "Smoking Room": 0.5,
    "Dark Room": 0.5,
    "Lumber Room": 0.5,
    "Nursery": 0.5,
    "Play Room": 0.5,
    "Tennis Court": 0.5,
    "Saucery": 0.5,
    "Scullery": 0.5,
    "Spicery": 0.5,
    "Sun Room": 0.5,
    "Seance Room": 0.5,
    "Reception Hall": 0.5,
    "Storage Closet": 0.5,
    "Hallway": 0.5,
    "Mirror Room": 0.5,
    "Torture Chamber": 0.5,
    "Veranda": 0.5,
    "Weaving/Needlepoint Room": 0.5,
    "Balcony": 0.5,
    "Pigeonnier": 0.5,
    "Humidor": 0.5,
    "Exercise Room": 0.5,
    "Walk-in Icebox": 0.5,
    "Apothecary": 0.5,
    "Observatory": 0.5,
    "Apiary": 0.5,
    "Coal Room": 0.5,
    "Telegraph Room": 0.5,
    "Guest House": 0.5,
    "Surgery": 0.5,
    "Still Room": 0.5,
    "Antechamber": 0.5,
    "Laundry Room": 0.5,
    "Courtyard": 0.5,
    "Oubliette": 0.5,
    "Roof": 0.5,
    "Crawl Space": 0.5,
    "Kennel": 0.5,
    "Elevator": 0.5,
    "Crypt": 0.5,
    "Museum": 0.5,
    "Menagerie": 0.5,
    "Chamber": 0.5,
    "Art Studio": 0.5,
    "Butchering Room": 0.5,
    "Aquarium": 0.5,
    "Display Room": 0.5
}

export const lightingTypes: AttributeList = {
    "Ambient": 0.5,
    "Brilliant": 0.5,
    "Cozy": 0.5,
    "Dim": 0.5,
    "Flickering": 0.5,
    "Glowing": 0.5,
    "Neon": 0.5,
    "Radiant": 0.5,
    "Serene": 0.5,
    "Twinkling": 0.5,
    "Vibrant": 0.5,
    "Warm": 0.5,
    "Florescent": 0.5,
    "Torchlit": 0.5,
    "Candlelit": 0.5,
    "Sunlit": 0.5,
    "Otherworldly": 0.5,
    "Spotlight": 0.5,
    "Harsh": 0.5,
    "Bright": 0.5,
    "Pitch-black": 0.5,
    "Shadowy": 0.5
}

export const locationConditions: AttributeList = {
    "Ruined": 0.5,
    "Dilapidated": 0.5,
    "Decaying": 0.5,
    "Worn": 0.5,
    "Weathered": 0.5,
    "Crumbled": 0.5,
    "Shattered": 0.5,
    "Eroded": 0.5,
    "Submerged": 0.5,
    "Flooded": 0.5,
    "Storm-battered": 0.5,
    "Neglected": 0.5,
    "Overgrown": 0.5,
    "Moss-covered": 0.5,
    "Lived-in": 0.5,
    "Abandoned": 0.5,
    "Empty": 0.5,
    "Desolate": 0.5,
    "Messy": 0.5,
    "Orderly": 0.5,
    "Pristine": 0.5,
    "Dusty": 0.5
}

export const locationTemperature: AttributeList = {
    "Freezing": 0.5,
    "Balmy": 0.5,
    "Frigid": 0.5,
    "Scorching": 0.5,
    "Chilly": 0.5,
    "Sweltering": 0.5,
    "Comfortable": 0.5,
    "Pleasant": 0.5,
    "Icy": 0.5,
    "Warm": 0.5,
    "Brisk": 0.5,
    "Cool": 0.5,
    "Frosty": 0.5,
    "Nippy": 0.5,
    "Mild": 0.5,
    "Cozy": 0.5,
    "Temperate": 0.5
}

export const locationSize: AttributeList = {
    "Large": 0.5,
    "Small": 0.5,
    "Spacious": 0.5,
    "Compact": 0.5,
    "Vast": 0.5,
    "Tiny": 0.5,
    "Expansive": 0.5,
    "Narrow": 0.5,
    "Wide": 0.5,
    "High": 0.5,
    "Low": 0.5,
    "Huge": 0.5,
    "Enormous": 0.5,
    "Average": 0.5,
    "Cramped": 0.5,
    "Cavernous": 0.5
}

export const locationSounds: AttributeList = {
    "Dripping water": 0.5,
    "Rain": 0.5,
    "Wind": 0.5,
    "Birds": 0.5,
    "Creaking": 0.5,
    "Rustling": 0.5,
    "Humming": 0.5,
    "Buzzing": 0.5,
    "Beeping": 0.5,
    "Footsteps": 0.5,
    "Whispering": 0.5,
    "Conversation": 0.5,
    "Talking": 0.5,
    "Silence": 0.5,
    "Music": 0.5
}

export const windowSize: AttributeList = {
    "Small": 0.5,
    "Average": 0.5,
    "Large": 0.5
}

export const windowStyle: AttributeList = {
    "Transom": 0.5,
    "Picture": 0.5,
    "Bay": 0.5,
    "Bow": 0.5,
    "Garden": 0.5,
    "Glass block": 0.5,
    "Skylight": 0.5,
    "Round": 0.5,
    "Arched": 0.5,
    "Half-moon": 0.5,
    "Dormer": 0.5,
    "Stained-glass": 0.5
}

export const windowCondition: AttributeList = {
    "Broken": 0.5,
    "Shattered": 0.5,
    "Cracked": 0.5,
    "Flaking": 0.5,
    "Splintered": 0.5,
    "Loose": 0.5,
    "Stuck": 0.5,
    "Leaking": 0.5,
    "Open": 0.5,
    "Closed": 0.5,
    "Ajar": 0.5,
    "Dirty": 0.5,
    "Grime-covered": 0.5,
    "Smudged": 0.5,
    "Dusty": 0.5,
    "Clean": 0.5,
    "Spotless": 0.5,
    "Streaked": 0.5,
    "Fogged": 0.5,
    "Burned": 0.5
}

export const exitSize: AttributeList = {
    "Small": 0.5,
    "Average": 0.5,
    "Large": 0.5
}

export const exitStyle: AttributeList = {
    "Panel": 0.5,
    "Sliding": 0.5,
    "Farm": 0.5,
    "Barn": 0.5,
    "Folding": 0.5,
    "French": 0.5,
    "Storm": 0.5,
    "Round": 0.5,
    "Roller": 0.5,
    "Revolving": 0.5,
    "Archway": 0.5
}

export const exitMaterial: AttributeList = {
    "Metal": 0.5,
    "Wood": 0.5,
    "Glass": 0.5,
    "Screen": 0.5
}

export const exitCondition: AttributeList = {
    "Broken": 0.5,
    "Shattered": 0.5,
    "Cracked": 0.5,
    "Flaking": 0.5,
    "Splintered": 0.5,
    "Loose": 0.5,
    "Stuck": 0.5,
    "Leaking": 0.5,
    "Open": 0.5,
    "Closed": 0.5,
    "Ajar": 0.5,
    "Dirty": 0.5,
    "Grime-covered": 0.5,
    "Smudged": 0.5,
    "Dusty": 0.5,
    "Clean": 0.5,
    "Spotless": 0.5,
    "Streaked": 0.5,
    "Burned": 0.5
}

export const locationScent: AttributeList = {
    "Musty": 0.5,
    "Smoky": 0.5,
    "Pleasant": 0.5
}

export const locationAtmospheres: AttributeList = {
    "Spooky": 0.5,
    "Eerie": 0.5,
    "Calm": 0.5,
    "Relaxing": 0.5,
    "Energetic": 0.5,
}

export const npcNames: AttributeList = {
    "Cregdec": 0.5,
    "Eularia Fajardo": 0.5,
    "Vav Baxrot": 0.5,
    "Berta Ahle": 0.5,
    "Gwyn": 0.5,
    "Renni": 0.5,
    "Aliyya al-Naqvi": 0.5
}

export const npcClasses: AttributeList = {
    "Artificer": 0.5,
    "Barbarian": 0.5,
    "Bard": 0.5,
    "Cleric": 0.5,
    "Druid": 0.5,
    "Fighter": 0.5,
    "Monk": 0.5,
    "Paladin": 0.5,
    "Ranger": 0.5,
    "Rogue": 0.5,
    "Sorcerer": 0.5,
    "Warlock": 0.5,
    "Wizard": 0.5,
    "Bandit": 0.5,
    "Berserker": 0.5,
    "Commoner": 0.5,
    "Cultist": 0.5,
    "Acolyte": 0.5,
    "Knight": 0.5,
    "Mage": 0.5,
    "Noble": 0.5,
    "Pirate": 0.5,
    "Priest": 0.5,
    "Scout": 0.5,
    "Guard": 0.5,
    "Thug": 0.5,
    "Vampire": 0.5,
    "Veteran": 0.5,
    "Warrior": 0.5,
}

export const npcRaces: AttributeList = {
    "Aasimar": 0.5,
    "Dragonborn": 0.5,
    "Dwarf": 0.5,
    "Elf": 0.5,
    "Gnome": 0.5,
    "Goliath": 0.5,
    "Halfling": 0.5,
    "Human": 0.5,
    "Orc": 0.5,
    "Tiefling": 0.5,
    "Dhampir": 0.5,
    "Faerie": 0.5,
    "Flamekin": 0.5,
    "Shifter": 0.5,
    "Changeling": 0.5,
    "Warforged": 0.5,
    "Aarakocra": 0.5,
    "Genasi": 0.5,
    "Bugbear": 0.5,
    "Centaur": 0.5,
    "Deep Gnome": 0.5,
    "Duergar": 0.5,
    "Eladrin": 0.5,
    "Firbolg": 0.5,
    "Githyanki": 0.5,
    "Githerzai": 0.5,
    "Goblin": 0.5,
    "Hobgoblin": 0.5,
    "Kenku": 0.5,
    "Kobold": 0.5,
    "Lizardfolk": 0.5,
    "Minotaur": 0.5,
    "Satyr": 0.5,
    "Tabaxi": 0.5,
    "Tortle": 0.5,
    "Triton": 0.5,
    "Yuan-ti": 0.5,
    "Leonin": 0.5,
    "Loxodon": 0.5,
    "Half-elf": 0.5,
    "Half-orc": 0.5,
}

export const creatureType = {
    "Dragon": 0.5,
    "Sphinx": 0.5,
    "Construct": 0.5,
    "Living plant": 0.5,
    "Badger": 0.5,
    "Bat": 0.5,
    "Devil": 0.5,
    "Demon": 0.5,
    "Bear": 0.5,
    "Ooze": 0.5,
    "Dog": 0.5,
    "Cat": 0.5,
    "Hawk": 0.5,
    "Chimera": 0.5,
    "Snake": 0.5,
    "Turtle": 0.5,
    "Dryad": 0.5,
    "Eagle": 0.5,
    "Elemental": 0.5,
    "Gargoyle": 0.5,
    "Gelatinous cube": 0.5,
    "Ghost": 0.5,
    "Goblin": 0.5,
    "Hag": 0.5,
    "Griffon": 0.5,
    "Harpy": 0.5,
    "Hound": 0.5,
    "Homunculus": 0.5,
    "Mephit": 0.5,
    "Imp": 0.5,
    "Kobold": 0.5,
    "Lizard": 0.5,
    "Manticore": 0.5,
    "Mimic": 0.5,
    "Mummy": 0.5,
    "Ogre": 0.5,
    "Owl": 0.5,
    "Panther": 0.5,
    "Pegasus": 0.5,
    "Rat": 0.5,
    "Raven": 0.5,
    "Satyr": 0.5,
    "Shadow": 0.5,
    "Skelton": 0.5,
    "Specter": 0.5,
    "Fairy": 0.5,
    "Tiger": 0.5,
    "Treant": 0.5,
    "Troll": 0.5,
    "Unicorn": 0.5,
    "Werewolf": 0.5,
    "Wolf": 0.5,
    "Wraith": 0.5,
    "Zombie": 0.5
}

export const creatureSize = {
    "Average": 0.5,
    "Huge": 0.5,
    "Small": 0.5,
    "Runty": 0.5,
    "Tiny": 0.5,
    "Slight": 0.5,
    "Heavy": 0.5
}

export const creatureCondition = {
    "Scarred": 0.5,
    "Blind": 0.5,
    "Deaf": 0.5,
    "Paralyzed": 0.5,
    "Missing a limb": 0.5,
    "Invisible": 0.5,
    "Poisoned": 0.5,
    "Restrained": 0.5,
    "Unconscious": 0.5,
    "Exhausted": 0.5,
    "Asleep": 0.5,
    "Normal": 0.5
}

export const creatureBehavior = {
    "Charmed": 0.5,
    "Frightened": 0.5,
    "Aggressive": 0.5,
    "Docile": 0.5,
    "Friendly": 0.5,
    "Tamed": 0.5,
}

export const itemType: AttributeList = {
    "Weapon": 0.5,
    "Armor": 0.5,
    "Table": 0.5,
    "Plant": 0.5,
    "Book": 0.5,
    "Scroll": 0.5,
    "Crate": 0.5,
    "Chest": 0.5,
    "Bookshelf": 0.5,
    "Chair": 0.5,
    "Desk": 0.5,
    "Gemstone": 0.5,
    "Jewel": 0.5,
    "Painting": 0.5,
    "Key": 0.5
}

export const itemCondition: AttributeList = {
    "Broken": 0.5,
    "Shattered": 0.5,
    "Cracked": 0.5,
    "Flaking": 0.5,
    "Splintered": 0.5,
    "Dirty": 0.5,
    "Grime-covered": 0.5,
    "Dusty": 0.5,
    "Clean": 0.5,
    "Burned": 0.5
}

export const trapType: AttributeList = {
    "Mechanical": 0.5,
    "Magical": 0.5
}

export const trapTrigger: AttributeList = {
    "Pressure plate": 0.5,
    "Tripwire": 0.5,
    "Doorknob": 0.5
}

export const trapEffect: AttributeList = {
    "Hidden arrow": 0.5,
    "Spike pit opens": 0.5,
    "Room starts flooding": 0.5,
    "Activator is poisoned": 0.5,
    "Blast of fire": 0.5,
}

export const trapDanger: AttributeList = {
    "Setback": 0.5,
    "Dangerous": 0.5,
    "Deadly": 0.5
}

// other attributes
// unique traits (larger than it seems, etc)