export const roomTypes: AttributeList = {
    "Porch": 0.5,
    "Foyer": 0.5,
    "Cloak room": 0.5,
    "Gallery": 0.5,
    "Great hall": 0.5,
    "Dining hall": 0.5,
    "Ballroom": 0.5,
    "Piano room": 0.5,
    "Billiard room": 0.5,
    "Drawing room": 0.5,
    "Study": 0.5,
    "Library": 0.5,
    "Conservatory": 0.5,
    "Trophy room": 0.5,
    "Armory": 0.5,
    "Shooting range": 0.5,
    "Indoor Pool": 0.5,
    "Stables": 0.5,
    "Tack Room": 0.5,
    "Groom's room": 0.5,
    "Coach House": 0.5,
    "Servant's Quarters": 0.5,
    "Silver polishing room": 0.5,
    "Gift wrapping room": 0.5,
    "Canning room": 0.5,
    "Wine cellar": 0.5,
    "Root cellar": 0.5,
    "Larder": 0.5,
    "Pantry": 0.5,
    "Butler's pantry": 0.5,
    "Family kitchen": 0.5,
    "Personal Dining Room": 0.5,
    "Parlor": 0.5,
    "Master Bedroom": 0.5,
    "Guest Bedroom": 0.5,
    "Dressing Room": 0.5,
    "Powder Room": 0.5,
    "Master Bathroom": 0.5,
    "Guest Bathroom": 0.5,
    "Garret": 0.5,
    "Attic": 0.5,
    "Belvedere": 0.5,
    "Theater": 0.5,
    "Topiary Maze": 0.5,
    "Panic Room": 0.5,
    "Sub-Basement": 0.5,
    "Atrium": 0.5,
    "Boudoir": 0.5,
    "Chapel": 0.5,
    "Fainting Room": 0.5,
    "Furnace Room": 0.5,
    "Sauna": 0.5,
    "Smoking Room": 0.5,
    "Dark Room": 0.5,
    "Lumber Room": 0.5,
    "Nursery": 0.5,
    "Play Room": 0.5,
    "Tennis Court": 0.5,
    "Saucery": 0.5,
    "Scullery": 0.5,
    "Spicery": 0.5,
    "Sun Room": 0.5,
    "Seance Room": 0.5,
    "Reception Hall": 0.5,
    "Storage Closet": 0.5,
    "Hallway": 0.5,
    "Mirror Room": 0.5,
    "Torture Chamber": 0.5,
    "Veranda": 0.5,
    "Weaving/Needlepoint Room": 0.5,
    "Balcony": 0.5,
    "Pigeonnier": 0.5,
    "Humidor": 0.5,
    "Exercise Room": 0.5,
    "Walk-in Icebox": 0.5,
    "Apothecary": 0.5,
    "Observatory": 0.5,
    "Apiary": 0.5,
    "Coal Room": 0.5,
    "Telegraph Room": 0.5,
    "Guest House": 0.5,
    "Surgery": 0.5,
    "Still Room": 0.5,
    "Antechamber": 0.5,
    "Laundry Room": 0.5,
    "Courtyard": 0.5,
    "Oubliette": 0.5,
    "Roof": 0.5,
    "Crawl Space": 0.5,
    "Kennel": 0.5,
    "Elevator": 0.5,
    "Crypt": 0.5,
    "Museum": 0.5,
    "Menagerie": 0.5,
    "Chamber": 0.5,
    "Art Studio": 0.5,
    "Butchering Room": 0.5,
    "Aquarium": 0.5,
    "Display Room": 0.5
}

export const lightingTypes: AttributeList = {
    "Ambient": 0.5,
    "Brilliant": 0.5,
    "Cozy": 0.5,
    "Dim": 0.5,
    "Flickering": 0.5,
    "Glowing": 0.5,
    "Neon": 0.5,
    "Radiant": 0.5,
    "Serene": 0.5,
    "Twinkling": 0.5,
    "Vibrant": 0.5,
    "Warm": 0.5,
    "Florescent": 0.5,
    "Torchlit": 0.5,
    "Candlelit": 0.5,
    "Sunlit": 0.5,
    "Otherworldly": 0.5,
    "Spotlight": 0.5,
    "Harsh": 0.5,
    "Bright": 0.5,
    "Pitch-black": 0.5,
    "Shadowy": 0.5
}

export const locationConditions: AttributeList = {
    "Ruined": 0.5,
    "Dilapidated": 0.5,
    "Decaying": 0.5,
    "Worn": 0.5,
    "Weathered": 0.5,
    "Crumbled": 0.5,
    "Shattered": 0.5,
    "Eroded": 0.5,
    "Submerged": 0.5,
    "Flooded": 0.5,
    "Storm-battered": 0.5,
    "Neglected": 0.5,
    "Overgrown": 0.5,
    "Moss-covered": 0.5,
    "Lived-in": 0.5,
    "Abandoned": 0.5,
    "Empty": 0.5,
    "Desolate": 0.5,
    "Messy": 0.5,
    "Orderly": 0.5,
    "Pristine": 0.5,
    "Dusty": 0.5
}

export const locationTemperature: AttributeList = {
    "Freezing": 0.5,
    "Balmy": 0.5,
    "Frigid": 0.5,
    "Scorching": 0.5,
    "Chilly": 0.5,
    "Sweltering": 0.5,
    "Comfortable": 0.5,
    "Pleasant": 0.5,
    "Icy": 0.5,
    "Warm": 0.5,
    "Brisk": 0.5,
    "Cool": 0.5,
    "Frosty": 0.5,
    "Nippy": 0.5,
    "Mild": 0.5,
    "Cozy": 0.5,
    "Temperate": 0.5
}

export const locationSize: AttributeList = {
    "Large": 0.5, 
    "Small": 0.5,
    "Spacious": 0.5,
    "Compact": 0.5,
    "Vast": 0.5,
    "Tiny": 0.5,
    "Expansive": 0.5,
    "Narrow": 0.5,
    "Wide": 0.5,
    "High": 0.5,
    "Low": 0.5,
    "Huge": 0.5,
    "Enormous": 0.5,
    "Average": 0.5,
    "Cramped": 0.5,
    "Cavernous": 0.5
}

export const windowSize: AttributeList = {
    "Small": 0.5,
    "Average": 0.5,
    "Large": 0.5
}

export const windowStyle: AttributeList = {
    "Transom": 0.5,
    "Picture": 0.5,
    "Bay": 0.5,
    "Bow": 0.5,
    "Garden": 0.5,
    "Glass block": 0.5,
    "Skylight": 0.5,
    "Round": 0.5,
    "Arched": 0.5,
    "Half-moon": 0.5,
    "Dormer": 0.5,
    "Stained-glass": 0.5
}

export const windowCondition: AttributeList = {
    "Broken": 0.5,
    "Shattered": 0.5,
    "Cracked": 0.5,
    "Flaking": 0.5,
    "Splintered": 0.5,
    "Loose": 0.5,
    "Stuck": 0.5,
    "Leaking": 0.5,
    "Open": 0.5,
    "Closed": 0.5,
    "Ajar": 0.5,
    "Dirty": 0.5,
    "Grime-covered": 0.5,
    "Smudged": 0.5,
    "Dusty": 0.5,
    "Clean": 0.5,
    "Spotless": 0.5,
    "Streaked": 0.5,
    "Fogged": 0.5,
    "Burned": 0.5
}

// other attributes
// sounds
// smells
// exits
// people
// creatures
// significant items
// unique traits (larger than it seems, etc)